# Generated by Django 5.2.8 on 2025-11-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['name']},
        ),
    ]
